brew update

brew upgrade

brew install augeas                          
brew install libplist
brew install autoconf                        
brew install libpng
brew install automake                        
brew install libspatialite
brew install bash-completion                 
brew install battery                         
brew install boost                           
brew install cairo                           
brew install certbot                         
brew install cmake                           
brew install coreutils                       
brew install curl                            
brew install dialog                          
brew install emojify                         
brew install exercism                        
brew install fontconfig                      
brew install fontforge                       
brew install freetype                        
brew install freexl                          
brew install fzf                             
brew install gcc                             
brew install gdal                            
brew install gdbm                            
brew install geos                            
brew install gettext                         
brew install gflags                          
brew install giflib                          
brew install glib                            
brew install gmp                             
brew install gobject-introspection           
brew install guetzli                         
brew install harfbuzz                        
brew install highlight                       
brew install icu4c                           
brew install ideviceinstaller                
brew install isl                             
brew install jemalloc                        
brew install jpeg                            
brew install json-c                          
brew install libevent                        
brew install libffi                          
brew install libgeotiff                      
brew install libimobiledevice                
brew install liblwgeom                       
brew install libmpc                          
brew install libtasn1
brew install libtermkey
brew install libtiff
brew install libtool
brew install libusb
brew install libuv
brew install libvterm
brew install libxml2
brew install libzip
brew install lua
brew install lzlib
brew install macvim
brew install mpfr
brew install msgpack
brew install neovim
brew install node
brew install openssl
brew install openssl@1.1
brew install pango
brew install pcre
brew install pixman
brew install pkg-config
brew install proj
brew install python
brew install readline
brew install reattach-to-user-namespace
brew install spark
brew install sqlite
brew install swiftlint
brew install the_silver_searcher
brew install tmux
brew install tree
brew install unibilium
brew install usbmuxd
brew install vim
brew install watchman
brew install wget
brew install xz
brew install yarn
brew install zsh
brew install zsh-syntax-highlighting

brew cleanup
